# Generated by Django 3.2.6 on 2023-02-26 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20230225_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likedpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postliked', to='network.post')),
                ('likes', models.ManyToManyField(blank=True, related_name='userlikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
