# Generated by Django 4.1.7 on 2023-03-19 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recipient1_active', models.BooleanField(default=True)),
                ('is_recipient2_active', models.BooleanField(default=True)),
                ('recipient1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver1', to=settings.AUTH_USER_MODEL)),
                ('recipient2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textmessage', models.TextField(default=None)),
                ('imagemessage', models.ImageField(default=None, upload_to='chats/images')),
                ('filemessage', models.FileField(default=None, upload_to='chats/files')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chatgroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chats', to='network.chat')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messagereceiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messagesender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
