# Generated by Django 4.1.7 on 2023-03-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_chat_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
